# -*- coding: utf-8 -*-
"""mmb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15b7PZp5ET6GoGk1svw_PJ_YyLLKK8Sth
"""

import numpy as np
from scipy import optimize

def sample_unit_sphere():
    vec = np.random.randn(3)
    vec = vec / np.linalg.norm(vec, axis=0)
    return vec

def compute_mmb(ocs_Phi, obs_resp_Phi, obs_resp_Psi, illum_Phi=None, illum_Psi=None, res=100):
    S = obs_resp_Psi
    S_Phi = obs_resp_Phi
    points = []
    for _ in range(res):
        k = sample_unit_sphere()
        x = optimize.linprog(c=S.T @ k, A_eq=S_Phi, b_eq=ocs_Phi, bounds=(0, 1)).x
        points.append((S @ x).tolist())
    return points
